### ISSUE TITLE
Allow setting PipelineDepth via ENV

### ISSUE THREAD

**Issue by MadWalnut** [jon6fingrs/mbsync#4]
Currently fetching from Yahoo Mail fails with `NO [UNAVAILABLE] UID FETCH Service is temporarily not available mbsync`. This is because Yahoo requires a smaller `PipelineDepth` value (like `4`) in `.mbsyncrc` instead of the default `1024`. [Ref](https://www.mail-archive.com/isync-devel@lists.sourceforge.net/msg03229.html)

It would be great if we could set that value in a Docker environment variable. This would require adding this line to `.mbsyncrc` and updating the Dockerfile accordingly:

`PipelineDepth {pipelinedepth}`

An update would be highly appreciated! Thanks.

**Comment by jon6fingrs** [comment]
ok i think i added an optional env variable to accomplish what you are asking.

I pushed the docker image with the tag "pipeline":

thehelpfulidiot/mbsync:pipeline

Use the environment variable "pipeline_depth". let me know if it works. i have not tested it. thanks!

**Comment by MadWalnut** [comment]
Thank you for the fast change! I tried the `pipeline` tag but I get these errors:

```
Reading configuration file /etc/.mbsyncrc
/etc/.mbsyncrc:11: keyword 'IMAPStore' is not recognized in IMAPAccount sections
/etc/.mbsyncrc:12: keyword 'Account' is not recognized in IMAPAccount sections
/etc/.mbsyncrc:13: keyword 'UseNamespace' is not recognized in IMAPAccount sections
/etc/.mbsyncrc:14: invalid integer value '{pipeline_depth}'
/etc/.mbsyncrc:14: PipelineDepth must be at least 1
/etc/.mbsyncrc:26: unknown store 'yahoo-remote'
channel 'yahoo' refers to no far side store
Notice: Master/Slave are deprecated; use Far/Near instead.
```

My thoughts:

1. I think we have to add the new ENV to the `run.sh` script, no? Because currently its just using the default `ENV pipeline_depth="1024"` line from the Dockerfile and not applying the updated value from `docker-compose.yml`.
2. This line however seems to be failing with `invalid integer value` because the quotation marks make it a string, rather than an integer. Maybe it should rather be `ENV pipeline_depth=1024`?
3. That line in the Dockerfile is also not commented out like the rest of the ENVs. Not sure if thats supposed to be that way, just pointing it out.

**Comment by jon6fingrs** [comment]
Ok try it now. I think I messed up the spacing initially. And for the pipeline depth env variable, don't use quotes as I think it needs to be an integer.

**Comment by MadWalnut** [comment]
Thanks for the update. I'm getting a step closer. It still fails though:

```
Reading configuration file /etc/.mbsyncrc
/etc/.mbsyncrc:11: invalid integer value '{pipeline_depth}'
/etc/.mbsyncrc:11: PipelineDepth must be at least 1
Notice: Master/Slave are deprecated; use Far/Near instead.
```

This is my `docker-compose.yml`:

```
mbsync2:
    image: thehelpfulidiot/mbsync:pipeline
    container_name: mbsync2
    restart: "no"
    volumes:
      - ./mail:/mail # Same as dovecot.
    environment:
      - host_name=imap.mail.yahoo.com
      - port=993
      - remote_username=XXX
      - remote_password=XXX
      - ssltype=IMAPS
      - sslversions=TLSv1.2
      - mailbox_name=yahoo
      - PUID=1000
      - pipeline_depth=4
```

So I am definitely setting it as an integer without quotes.

I can't see your newest commit (probably not pushed yet), but my guess is, that it is still using the value from your [Dockerfile](https://github.com/jon6fingrs/mbsync/blob/pipeline/dockerfile), which is in quotes. I don't think my integer value `4` is being set at all, because the `sed` line is missing in `run.sh`.

I believe I fixed it in my [pull request](https://github.com/jon6fingrs/mbsync/pull/6). I currently can't build to test it right now, but if you merge to your pipeline branch and build it, I am happy to try by pulling from Docker Hub!
